# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-03 07:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0023_migrate-alias-slug'),
        ('oauth', '0008_add-project-relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Publisher Metadata')),
                ('projects_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Projects Metadata')),
                ('config_repo_name', models.CharField(default='docs-italia-conf', max_length=255, verbose_name='Docs italia config repo')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('remote_organization', models.ManyToManyField(to='oauth.RemoteOrganization', verbose_name='Remote organization')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='Metadata')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('projects', models.ManyToManyField(to='projects.Project', verbose_name='Projects')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsitalia.Publisher', verbose_name='Publisher')),
            ],
        ),
    ]
