# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-04 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='remote_organization',
            field=models.ManyToManyField(blank=True, to='oauth.RemoteOrganization', verbose_name='Remote organization'),
        ),
    ]
