# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-04 10:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0002_auto_20180404_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Publisher Metadata'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='projects_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Projects Metadata'),
        ),
        migrations.AlterField(
            model_name='publisherproject',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Metadata'),
        ),
    ]
