# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 08:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0004_auto_20180411_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('github_webhook', 'GitHub incoming webhook')], max_length=32, verbose_name='Integration type')),
                ('provider_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Provider data')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='docsitalia.Publisher')),
            ],
        ),
    ]
