# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0005_publisherintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherproject',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
