# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0006_publisherproject_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='active',
            field=models.BooleanField(default=False, help_text='Enables the import of documents.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Publisher\'s name in full. You can refer to the "name" field from "publisher_settings.yml", e.g. Ministero della Documentazione.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(help_text='Pick the URL fragment following "https://github.com" in the organization URL, e.g ministero-della-documentazione.', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
