# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-06 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0007_auto_20180606_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='active',
            field=models.BooleanField(default=True, help_text='Enables the import of documents.', verbose_name='Active'),
        ),
    ]
