# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0009_auto_20180613_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='config_repo_name',
            field=models.CharField(default='italia-conf', max_length=255, verbose_name='Docs italia config repo'),
        ),
    ]
