# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-26 05:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0010_auto_20180726_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Publisher Metadata'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='projects_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Projects Metadata'),
        ),
        migrations.AlterField(
            model_name='publisherintegration',
            name='provider_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Provider data'),
        ),
        migrations.AlterField(
            model_name='publisherproject',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
    ]
