# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0012_auto_20180814_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='remote_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth.RemoteOrganization', verbose_name='Remote organization'),
        ),
    ]
