# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0013_auto_20181029_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'allowed tag',
                'verbose_name_plural': 'allowed tags',
                'ordering': ('name',),
            },
        ),
    ]
