# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-17 11:49
from __future__ import unicode_literals

from django.db import migrations

from readthedocs.docsitalia.models import AllowedTag


class Migration(migrations.Migration):

    dependencies = [
        ('docsitalia', '0014_allowedtag'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: AllowedTag.objects.bulk_create(
                [AllowedTag(name=tag, enabled=True) for tag in AllowedTag.BASE_TAGS],
            ),
        ),
    ]
