# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-05 01:06
from __future__ import unicode_literals

from django.db import migrations


FEATURE = 'use_sphinx_latest'
DESCRIPTION = 'Use latest Sphinx version'


def add_feature(apps, schema_editor):
    Feature = apps.get_model('projects', 'Feature')
    (_, created) = Feature.objects.get_or_create(
        feature=FEATURE,
        description=DESCRIPTION
    )


def remove_feature(apps, schema_editor):
    Feature = apps.get_model('projects', 'Feature')
    Feature.objects.filter(feature=FEATURE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_add-feature-flags'),
    ]

    operations = [
        migrations.RunPython(add_feature, remove_feature)
    ]
